import { ScaleInterval } from "./Types";
import { Interval } from "../Interval/__Main__";
import { Note } from "../Note/__Main__";
import { NoteName, MidiValue, Pitch } from "../Note/Types";
import { RelativeTime } from "@/Time/__Main__";
export declare class Scale {
    readonly intervals: Interval[];
    constructor(...intervals: (Interval | ScaleInterval)[]);
    notes(root: Pitch, options?: {
        from?: (Note | NoteName | MidiValue);
        to?: (Note | NoteName | MidiValue);
        velocity?: MidiValue;
        duration?: (number | string | RelativeTime | RelativeTime.Components);
        delay?: (number | string | RelativeTime | RelativeTime.Components);
    }): Note[];
}
export declare namespace Scale {
    const Chromatic: Scale, Ionian: Scale, Dorian: Scale, Phrygian: Scale, Lydian: Scale, Mixolydian: Scale, Aeolian: Scale, Locrian: Scale, Aeolian_HarmonicMinor: Scale, Locrian_HarmonicMinor_1: Scale, Ionian_HarmonicMinor: Scale, Dorian_HarmonicMinor: Scale, Phrygian_HarmonicMinor: Scale, Lydian_HarmonicMinor: Scale, Locrian_HarmonicMinor_2: Scale, Aeolian_MelodicMinor_1: Scale, Phrygian_MelodicMinor: Scale, Lydian_MelodicMinor_1: Scale, Lydian_MelodicMinor_2: Scale, Aeolian_MelodicMinor_2: Scale, Locrian_MelodicMinor_1: Scale, Locrian_MelodicMinor_2: Scale, Major: Scale, HarmonicMinor: Scale, MelodicMinor: Scale, NaturalMinor: Scale, Bebop_Dominant: Scale, Bebop_Major: Scale, Bebop_HarmonicMinor: Scale, Bebop_MelodicMinor: Scale, Blues_Major: Scale, Blues_Minor: Scale, Blues_Diminished: Scale, Blues_Pentatonic: Scale, Blues_Rock: Scale, Gypsy_Major: Scale, Gypsy_Minor: Scale, Gypsy_Hungarian: Scale, Gypsy_Spanish: Scale, Pentatonic_Major: Scale, Pentatonic_Neutral: Scale, Pentatonic_Rock: Scale, Pentatonic_Scottish: Scale, Pentatonic_Minor: Scale, WholeTone: Scale, Whole_Half: Scale, Half_Whole: Scale, Augmented: Scale, Byzantine: Scale, Enigmatic_Ascending: Scale, Enigmatic_Descending: Scale, Hungarian_Major: Scale, Hungarian_Minor: Scale, Neapolitan_Major: Scale, Neapolitan_Minor: Scale, Overtone: Scale, Prometheus: Scale, Prometheus_Neapolitan: Scale, Spanish_8_Tone: Scale;
    const A: _Scale.DefaultScales;
    const Bb: _Scale.DefaultScales;
    const A$: _Scale.DefaultScales;
    const B: _Scale.DefaultScales;
    const C: _Scale.DefaultScales;
    const C$: _Scale.DefaultScales;
    const Db: _Scale.DefaultScales;
    const D: _Scale.DefaultScales;
    const Eb: _Scale.DefaultScales;
    const D$: _Scale.DefaultScales;
    const E: _Scale.DefaultScales;
    const F: _Scale.DefaultScales;
    const F$: _Scale.DefaultScales;
    const Gb: _Scale.DefaultScales;
    const G: _Scale.DefaultScales;
    const G$: _Scale.DefaultScales;
    const Ab: _Scale.DefaultScales;
}
export declare namespace _Scale {
    type DefaultScales = {
        Chromatic: Note[];
        Ionian: Note[];
        Dorian: Note[];
        Phrygian: Note[];
        Lydian: Note[];
        Mixolydian: Note[];
        Aeolian: Note[];
        Locrian: Note[];
        Aeolian_HarmonicMinor: Note[];
        Locrian_HarmonicMinor_1: Note[];
        Ionian_HarmonicMinor: Note[];
        Dorian_HarmonicMinor: Note[];
        Phrygian_HarmonicMinor: Note[];
        Lydian_HarmonicMinor: Note[];
        Locrian_HarmonicMinor_2: Note[];
        Aeolian_MelodicMinor_1: Note[];
        Phrygian_MelodicMinor: Note[];
        Lydian_MelodicMinor_1: Note[];
        Lydian_MelodicMinor_2: Note[];
        Aeolian_MelodicMinor_2: Note[];
        Locrian_MelodicMinor_1: Note[];
        Locrian_MelodicMinor_2: Note[];
        Major: Note[];
        HarmonicMinor: Note[];
        MelodicMinor: Note[];
        NaturalMinor: Note[];
        Bebop_Dominant: Note[];
        Bebop_Major: Note[];
        Bebop_HarmonicMinor: Note[];
        Bebop_MelodicMinor: Note[];
        Blues_Major: Note[];
        Blues_Minor: Note[];
        Blues_Diminished: Note[];
        Blues_Pentatonic: Note[];
        Blues_Rock: Note[];
        Gypsy_Major: Note[];
        Gypsy_Minor: Note[];
        Gypsy_Hungarian: Note[];
        Gypsy_Spanish: Note[];
        Pentatonic_Major: Note[];
        Pentatonic_Neutral: Note[];
        Pentatonic_Rock: Note[];
        Pentatonic_Scottish: Note[];
        Pentatonic_Minor: Note[];
        WholeTone: Note[];
        Whole_Half: Note[];
        Half_Whole: Note[];
        Augmented: Note[];
        Byzantine: Note[];
        Enigmatic_Ascending: Note[];
        Enigmatic_Descending: Note[];
        Hungarian_Major: Note[];
        Hungarian_Minor: Note[];
        Neapolitan_Major: Note[];
        Neapolitan_Minor: Note[];
        Overtone: Note[];
        Prometheus: Note[];
        Prometheus_Neapolitan: Note[];
        Spanish_8_Tone: Note[];
    };
}
