//###  Module  ###//
import {Interval} from "../__Main__"


//##########################//
//###  Test.constructor  ###//
//##########################//

test("constructor", ()=>{
	expect(new Interval(0 )).toMatchObject(Interval.P1 )
	expect(new Interval(1 )).toMatchObject(Interval.m2 )
	expect(new Interval(2 )).toMatchObject(Interval.M2 )
	expect(new Interval(3 )).toMatchObject(Interval.m3 )
	expect(new Interval(4 )).toMatchObject(Interval.M3 )
	expect(new Interval(5 )).toMatchObject(Interval.P4 )
	expect(new Interval(6 )).toMatchObject(Interval.d5 )
	expect(new Interval(7 )).toMatchObject(Interval.P5 )
	expect(new Interval(8 )).toMatchObject(Interval.m6 )
	expect(new Interval(9 )).toMatchObject(Interval.M6 )
	expect(new Interval(10)).toMatchObject(Interval.m7 )
	expect(new Interval(11)).toMatchObject(Interval.M7 )
	expect(new Interval(12)).toMatchObject(Interval.P8 )
	expect(new Interval(13)).toMatchObject(Interval.m9 )
	expect(new Interval(14)).toMatchObject(Interval.M9 )
	expect(new Interval(15)).toMatchObject(Interval.m10)
	expect(new Interval(16)).toMatchObject(Interval.M10)
	expect(new Interval(17)).toMatchObject(Interval.P11)
	expect(new Interval(18)).toMatchObject(Interval.d12)
	expect(new Interval(19)).toMatchObject(Interval.P12)
	expect(new Interval(20)).toMatchObject(Interval.m13)
	expect(new Interval(21)).toMatchObject(Interval.M13)
	expect(new Interval(22)).toMatchObject(Interval.m14)
	expect(new Interval(23)).toMatchObject(Interval.M14)
	expect(new Interval(24)).toMatchObject(Interval.P15)

	expect(new Interval(25)).toMatchObject({relativeValue:16, absoluteValue:25, shortName:"m16", longName:"Minor 16th",         shortType:"m", longType:"Minor"     })
	expect(new Interval(26)).toMatchObject({relativeValue:16, absoluteValue:26, shortName:"M16", longName:"Major 16th",         shortType:"M", longType:"Major"     })
	expect(new Interval(27)).toMatchObject({relativeValue:17, absoluteValue:27, shortName:"m17", longName:"Minor 17th",         shortType:"m", longType:"Minor"     })
	expect(new Interval(28)).toMatchObject({relativeValue:17, absoluteValue:28, shortName:"M17", longName:"Major 17th",         shortType:"M", longType:"Major"     })
	expect(new Interval(29)).toMatchObject({relativeValue:18, absoluteValue:29, shortName:"P18", longName:"Perfect 18th",       shortType:"P", longType:"Perfect"   })
	expect(new Interval(30)).toMatchObject({relativeValue:19, absoluteValue:30, shortName:"d19", longName:"2nd Tritone Octave", shortType:"d", longType:"Diminished"})
	expect(new Interval(31)).toMatchObject({relativeValue:19, absoluteValue:31, shortName:"P19", longName:"Perfect 19th",       shortType:"P", longType:"Perfect"   })
	expect(new Interval(32)).toMatchObject({relativeValue:20, absoluteValue:32, shortName:"m20", longName:"Minor 20th",         shortType:"m", longType:"Minor"     })
	expect(new Interval(33)).toMatchObject({relativeValue:20, absoluteValue:33, shortName:"M20", longName:"Major 20th",         shortType:"M", longType:"Major"     })
	expect(new Interval(34)).toMatchObject({relativeValue:21, absoluteValue:34, shortName:"m21", longName:"Minor 21st",         shortType:"m", longType:"Minor"     })
	expect(new Interval(35)).toMatchObject({relativeValue:21, absoluteValue:35, shortName:"M21", longName:"Major 21st",         shortType:"M", longType:"Major"     })
	expect(new Interval(36)).toMatchObject({relativeValue:22, absoluteValue:36, shortName:"P22", longName:"3rd Octave",         shortType:"P", longType:"Perfect"   })
	expect(new Interval(37)).toMatchObject({relativeValue:23, absoluteValue:37, shortName:"m23", longName:"Minor 23rd",         shortType:"m", longType:"Minor"     })
	expect(new Interval(38)).toMatchObject({relativeValue:23, absoluteValue:38, shortName:"M23", longName:"Major 23rd",         shortType:"M", longType:"Major"     })
	expect(new Interval(39)).toMatchObject({relativeValue:24, absoluteValue:39, shortName:"m24", longName:"Minor 24th",         shortType:"m", longType:"Minor"     })
	expect(new Interval(40)).toMatchObject({relativeValue:24, absoluteValue:40, shortName:"M24", longName:"Major 24th",         shortType:"M", longType:"Major"     })
	expect(new Interval(41)).toMatchObject({relativeValue:25, absoluteValue:41, shortName:"P25", longName:"Perfect 25th",       shortType:"P", longType:"Perfect"   })
	expect(new Interval(42)).toMatchObject({relativeValue:26, absoluteValue:42, shortName:"d26", longName:"3rd Tritone Octave", shortType:"d", longType:"Diminished"})
	expect(new Interval(43)).toMatchObject({relativeValue:26, absoluteValue:43, shortName:"P26", longName:"Perfect 26th",       shortType:"P", longType:"Perfect"   })
	expect(new Interval(44)).toMatchObject({relativeValue:27, absoluteValue:44, shortName:"m27", longName:"Minor 27th",         shortType:"m", longType:"Minor"     })
	expect(new Interval(45)).toMatchObject({relativeValue:27, absoluteValue:45, shortName:"M27", longName:"Major 27th",         shortType:"M", longType:"Major"     })
	expect(new Interval(46)).toMatchObject({relativeValue:28, absoluteValue:46, shortName:"m28", longName:"Minor 28th",         shortType:"m", longType:"Minor"     })
	expect(new Interval(47)).toMatchObject({relativeValue:28, absoluteValue:47, shortName:"M28", longName:"Major 28th",         shortType:"M", longType:"Major"     })
	expect(new Interval(48)).toMatchObject({relativeValue:29, absoluteValue:48, shortName:"P29", longName:"4th Octave",         shortType:"P", longType:"Perfect"   })
})
