//###  Module  ###//
import {Note     }   from "../__Main__"
import {_NoteData}   from "../DefaultInstances"
import DefaultValues from "../DefaultValues"


//############################//
//###  Test.DefaultValues  ###//
//############################//

test("DefaultValues", ()=>{
	const defaultValues = {
		..._NoteData[85 ].data,
		velocity:  DefaultValues.velocity,
		_duration: DefaultValues.duration,
		_delay:    DefaultValues.delay,
	}

	expect(Note.C4               ).toMatchObject(defaultValues)
	expect(new Note("C4")        ).toMatchObject(defaultValues)
	expect(new Note(60  )        ).toMatchObject(defaultValues)
	expect(Note.C4       .clone()).toMatchObject(defaultValues)
	expect(new Note("C4").clone()).toMatchObject(defaultValues)
	expect(new Note(60  ).clone()).toMatchObject(defaultValues)
})


//#######################//
//###  Test.NoteName  ###//
//#######################//

test("NoteName", ()=>{
	expect(new Note("C-1" )).toMatchObject(_NoteData[0  ].data)
	expect(new Note("C#-1")).toMatchObject(_NoteData[1  ].data)
	expect(new Note("Db-1")).toMatchObject(_NoteData[2  ].data)
	expect(new Note("D-1" )).toMatchObject(_NoteData[3  ].data)
	expect(new Note("D#-1")).toMatchObject(_NoteData[4  ].data)
	expect(new Note("Eb-1")).toMatchObject(_NoteData[5  ].data)
	expect(new Note("E-1" )).toMatchObject(_NoteData[6  ].data)
	expect(new Note("F-1" )).toMatchObject(_NoteData[7  ].data)
	expect(new Note("F#-1")).toMatchObject(_NoteData[8  ].data)
	expect(new Note("Gb-1")).toMatchObject(_NoteData[9  ].data)
	expect(new Note("G-1" )).toMatchObject(_NoteData[10 ].data)
	expect(new Note("G#-1")).toMatchObject(_NoteData[11 ].data)
	expect(new Note("Ab-1")).toMatchObject(_NoteData[12 ].data)
	expect(new Note("A-1" )).toMatchObject(_NoteData[13 ].data)
	expect(new Note("A#-1")).toMatchObject(_NoteData[14 ].data)
	expect(new Note("Bb-1")).toMatchObject(_NoteData[15 ].data)
	expect(new Note("B-1" )).toMatchObject(_NoteData[16 ].data)
	expect(new Note("C0"  )).toMatchObject(_NoteData[17 ].data)
	expect(new Note("C#0" )).toMatchObject(_NoteData[18 ].data)
	expect(new Note("Db0" )).toMatchObject(_NoteData[19 ].data)
	expect(new Note("D0"  )).toMatchObject(_NoteData[20 ].data)
	expect(new Note("D#0" )).toMatchObject(_NoteData[21 ].data)
	expect(new Note("Eb0" )).toMatchObject(_NoteData[22 ].data)
	expect(new Note("E0"  )).toMatchObject(_NoteData[23 ].data)
	expect(new Note("F0"  )).toMatchObject(_NoteData[24 ].data)
	expect(new Note("F#0" )).toMatchObject(_NoteData[25 ].data)
	expect(new Note("Gb0" )).toMatchObject(_NoteData[26 ].data)
	expect(new Note("G0"  )).toMatchObject(_NoteData[27 ].data)
	expect(new Note("G#0" )).toMatchObject(_NoteData[28 ].data)
	expect(new Note("Ab0" )).toMatchObject(_NoteData[29 ].data)
	expect(new Note("A0"  )).toMatchObject(_NoteData[30 ].data)
	expect(new Note("A#0" )).toMatchObject(_NoteData[31 ].data)
	expect(new Note("Bb0" )).toMatchObject(_NoteData[32 ].data)
	expect(new Note("B0"  )).toMatchObject(_NoteData[33 ].data)
	expect(new Note("C1"  )).toMatchObject(_NoteData[34 ].data)
	expect(new Note("C#1" )).toMatchObject(_NoteData[35 ].data)
	expect(new Note("Db1" )).toMatchObject(_NoteData[36 ].data)
	expect(new Note("D1"  )).toMatchObject(_NoteData[37 ].data)
	expect(new Note("D#1" )).toMatchObject(_NoteData[38 ].data)
	expect(new Note("Eb1" )).toMatchObject(_NoteData[39 ].data)
	expect(new Note("E1"  )).toMatchObject(_NoteData[40 ].data)
	expect(new Note("F1"  )).toMatchObject(_NoteData[41 ].data)
	expect(new Note("F#1" )).toMatchObject(_NoteData[42 ].data)
	expect(new Note("Gb1" )).toMatchObject(_NoteData[43 ].data)
	expect(new Note("G1"  )).toMatchObject(_NoteData[44 ].data)
	expect(new Note("G#1" )).toMatchObject(_NoteData[45 ].data)
	expect(new Note("Ab1" )).toMatchObject(_NoteData[46 ].data)
	expect(new Note("A1"  )).toMatchObject(_NoteData[47 ].data)
	expect(new Note("A#1" )).toMatchObject(_NoteData[48 ].data)
	expect(new Note("Bb1" )).toMatchObject(_NoteData[49 ].data)
	expect(new Note("B1"  )).toMatchObject(_NoteData[50 ].data)
	expect(new Note("C2"  )).toMatchObject(_NoteData[51 ].data)
	expect(new Note("C#2" )).toMatchObject(_NoteData[52 ].data)
	expect(new Note("Db2" )).toMatchObject(_NoteData[53 ].data)
	expect(new Note("D2"  )).toMatchObject(_NoteData[54 ].data)
	expect(new Note("D#2" )).toMatchObject(_NoteData[55 ].data)
	expect(new Note("Eb2" )).toMatchObject(_NoteData[56 ].data)
	expect(new Note("E2"  )).toMatchObject(_NoteData[57 ].data)
	expect(new Note("F2"  )).toMatchObject(_NoteData[58 ].data)
	expect(new Note("F#2" )).toMatchObject(_NoteData[59 ].data)
	expect(new Note("Gb2" )).toMatchObject(_NoteData[60 ].data)
	expect(new Note("G2"  )).toMatchObject(_NoteData[61 ].data)
	expect(new Note("G#2" )).toMatchObject(_NoteData[62 ].data)
	expect(new Note("Ab2" )).toMatchObject(_NoteData[63 ].data)
	expect(new Note("A2"  )).toMatchObject(_NoteData[64 ].data)
	expect(new Note("A#2" )).toMatchObject(_NoteData[65 ].data)
	expect(new Note("Bb2" )).toMatchObject(_NoteData[66 ].data)
	expect(new Note("B2"  )).toMatchObject(_NoteData[67 ].data)
	expect(new Note("C3"  )).toMatchObject(_NoteData[68 ].data)
	expect(new Note("C#3" )).toMatchObject(_NoteData[69 ].data)
	expect(new Note("Db3" )).toMatchObject(_NoteData[70 ].data)
	expect(new Note("D3"  )).toMatchObject(_NoteData[71 ].data)
	expect(new Note("D#3" )).toMatchObject(_NoteData[72 ].data)
	expect(new Note("Eb3" )).toMatchObject(_NoteData[73 ].data)
	expect(new Note("E3"  )).toMatchObject(_NoteData[74 ].data)
	expect(new Note("F3"  )).toMatchObject(_NoteData[75 ].data)
	expect(new Note("F#3" )).toMatchObject(_NoteData[76 ].data)
	expect(new Note("Gb3" )).toMatchObject(_NoteData[77 ].data)
	expect(new Note("G3"  )).toMatchObject(_NoteData[78 ].data)
	expect(new Note("G#3" )).toMatchObject(_NoteData[79 ].data)
	expect(new Note("Ab3" )).toMatchObject(_NoteData[80 ].data)
	expect(new Note("A3"  )).toMatchObject(_NoteData[81 ].data)
	expect(new Note("A#3" )).toMatchObject(_NoteData[82 ].data)
	expect(new Note("Bb3" )).toMatchObject(_NoteData[83 ].data)
	expect(new Note("B3"  )).toMatchObject(_NoteData[84 ].data)
	expect(new Note("C4"  )).toMatchObject(_NoteData[85 ].data)
	expect(new Note("C#4" )).toMatchObject(_NoteData[86 ].data)
	expect(new Note("Db4" )).toMatchObject(_NoteData[87 ].data)
	expect(new Note("D4"  )).toMatchObject(_NoteData[88 ].data)
	expect(new Note("D#4" )).toMatchObject(_NoteData[89 ].data)
	expect(new Note("Eb4" )).toMatchObject(_NoteData[90 ].data)
	expect(new Note("E4"  )).toMatchObject(_NoteData[91 ].data)
	expect(new Note("F4"  )).toMatchObject(_NoteData[92 ].data)
	expect(new Note("F#4" )).toMatchObject(_NoteData[93 ].data)
	expect(new Note("Gb4" )).toMatchObject(_NoteData[94 ].data)
	expect(new Note("G4"  )).toMatchObject(_NoteData[95 ].data)
	expect(new Note("G#4" )).toMatchObject(_NoteData[96 ].data)
	expect(new Note("Ab4" )).toMatchObject(_NoteData[97 ].data)
	expect(new Note("A4"  )).toMatchObject(_NoteData[98 ].data)
	expect(new Note("A#4" )).toMatchObject(_NoteData[99 ].data)
	expect(new Note("Bb4" )).toMatchObject(_NoteData[100].data)
	expect(new Note("B4"  )).toMatchObject(_NoteData[101].data)
	expect(new Note("C5"  )).toMatchObject(_NoteData[102].data)
	expect(new Note("C#5" )).toMatchObject(_NoteData[103].data)
	expect(new Note("Db5" )).toMatchObject(_NoteData[104].data)
	expect(new Note("D5"  )).toMatchObject(_NoteData[105].data)
	expect(new Note("D#5" )).toMatchObject(_NoteData[106].data)
	expect(new Note("Eb5" )).toMatchObject(_NoteData[107].data)
	expect(new Note("E5"  )).toMatchObject(_NoteData[108].data)
	expect(new Note("F5"  )).toMatchObject(_NoteData[109].data)
	expect(new Note("F#5" )).toMatchObject(_NoteData[110].data)
	expect(new Note("Gb5" )).toMatchObject(_NoteData[111].data)
	expect(new Note("G5"  )).toMatchObject(_NoteData[112].data)
	expect(new Note("G#5" )).toMatchObject(_NoteData[113].data)
	expect(new Note("Ab5" )).toMatchObject(_NoteData[114].data)
	expect(new Note("A5"  )).toMatchObject(_NoteData[115].data)
	expect(new Note("A#5" )).toMatchObject(_NoteData[116].data)
	expect(new Note("Bb5" )).toMatchObject(_NoteData[117].data)
	expect(new Note("B5"  )).toMatchObject(_NoteData[118].data)
	expect(new Note("C6"  )).toMatchObject(_NoteData[119].data)
	expect(new Note("C#6" )).toMatchObject(_NoteData[120].data)
	expect(new Note("Db6" )).toMatchObject(_NoteData[121].data)
	expect(new Note("D6"  )).toMatchObject(_NoteData[122].data)
	expect(new Note("D#6" )).toMatchObject(_NoteData[123].data)
	expect(new Note("Eb6" )).toMatchObject(_NoteData[124].data)
	expect(new Note("E6"  )).toMatchObject(_NoteData[125].data)
	expect(new Note("F6"  )).toMatchObject(_NoteData[126].data)
	expect(new Note("F#6" )).toMatchObject(_NoteData[127].data)
	expect(new Note("Gb6" )).toMatchObject(_NoteData[128].data)
	expect(new Note("G6"  )).toMatchObject(_NoteData[129].data)
	expect(new Note("G#6" )).toMatchObject(_NoteData[130].data)
	expect(new Note("Ab6" )).toMatchObject(_NoteData[131].data)
	expect(new Note("A6"  )).toMatchObject(_NoteData[132].data)
	expect(new Note("A#6" )).toMatchObject(_NoteData[133].data)
	expect(new Note("Bb6" )).toMatchObject(_NoteData[134].data)
	expect(new Note("B6"  )).toMatchObject(_NoteData[135].data)
	expect(new Note("C7"  )).toMatchObject(_NoteData[136].data)
	expect(new Note("C#7" )).toMatchObject(_NoteData[137].data)
	expect(new Note("Db7" )).toMatchObject(_NoteData[138].data)
	expect(new Note("D7"  )).toMatchObject(_NoteData[139].data)
	expect(new Note("D#7" )).toMatchObject(_NoteData[140].data)
	expect(new Note("Eb7" )).toMatchObject(_NoteData[141].data)
	expect(new Note("E7"  )).toMatchObject(_NoteData[142].data)
	expect(new Note("F7"  )).toMatchObject(_NoteData[143].data)
	expect(new Note("F#7" )).toMatchObject(_NoteData[144].data)
	expect(new Note("Gb7" )).toMatchObject(_NoteData[145].data)
	expect(new Note("G7"  )).toMatchObject(_NoteData[146].data)
	expect(new Note("G#7" )).toMatchObject(_NoteData[147].data)
	expect(new Note("Ab7" )).toMatchObject(_NoteData[148].data)
	expect(new Note("A7"  )).toMatchObject(_NoteData[149].data)
	expect(new Note("A#7" )).toMatchObject(_NoteData[150].data)
	expect(new Note("Bb7" )).toMatchObject(_NoteData[151].data)
	expect(new Note("B7"  )).toMatchObject(_NoteData[152].data)
	expect(new Note("C8"  )).toMatchObject(_NoteData[153].data)
	expect(new Note("C#8" )).toMatchObject(_NoteData[154].data)
	expect(new Note("Db8" )).toMatchObject(_NoteData[155].data)
	expect(new Note("D8"  )).toMatchObject(_NoteData[156].data)
	expect(new Note("D#8" )).toMatchObject(_NoteData[157].data)
	expect(new Note("Eb8" )).toMatchObject(_NoteData[158].data)
	expect(new Note("E8"  )).toMatchObject(_NoteData[159].data)
	expect(new Note("F8"  )).toMatchObject(_NoteData[160].data)
	expect(new Note("F#8" )).toMatchObject(_NoteData[161].data)
	expect(new Note("Gb8" )).toMatchObject(_NoteData[162].data)
	expect(new Note("G8"  )).toMatchObject(_NoteData[163].data)
	expect(new Note("G#8" )).toMatchObject(_NoteData[164].data)
	expect(new Note("Ab8" )).toMatchObject(_NoteData[165].data)
	expect(new Note("A8"  )).toMatchObject(_NoteData[166].data)
	expect(new Note("A#8" )).toMatchObject(_NoteData[167].data)
	expect(new Note("Bb8" )).toMatchObject(_NoteData[168].data)
	expect(new Note("B8"  )).toMatchObject(_NoteData[169].data)
	expect(new Note("C9"  )).toMatchObject(_NoteData[170].data)
	expect(new Note("C#9" )).toMatchObject(_NoteData[171].data)
	expect(new Note("Db9" )).toMatchObject(_NoteData[172].data)
	expect(new Note("D9"  )).toMatchObject(_NoteData[173].data)
	expect(new Note("D#9" )).toMatchObject(_NoteData[174].data)
	expect(new Note("Eb9" )).toMatchObject(_NoteData[175].data)
	expect(new Note("E9"  )).toMatchObject(_NoteData[176].data)
	expect(new Note("F9"  )).toMatchObject(_NoteData[177].data)
	expect(new Note("F#9" )).toMatchObject(_NoteData[178].data)
	expect(new Note("Gb9" )).toMatchObject(_NoteData[179].data)
	expect(new Note("G9"  )).toMatchObject(_NoteData[180].data)
})


//########################//
//###  Test.MidiValue  ###//
//########################//

test("MidiValue", ()=>{
	// MIDI values correspond to _NoteData values after
	// indexes of flat notes have been removed
	expect(new Note(0  )).toMatchObject(_NoteData[0  ].data)
	expect(new Note(1  )).toMatchObject(_NoteData[1  ].data)
	expect(new Note(2  )).toMatchObject(_NoteData[3  ].data)
	expect(new Note(3  )).toMatchObject(_NoteData[4  ].data)
	expect(new Note(4  )).toMatchObject(_NoteData[6  ].data)
	expect(new Note(5  )).toMatchObject(_NoteData[7  ].data)
	expect(new Note(6  )).toMatchObject(_NoteData[8  ].data)
	expect(new Note(7  )).toMatchObject(_NoteData[10 ].data)
	expect(new Note(8  )).toMatchObject(_NoteData[11 ].data)
	expect(new Note(9  )).toMatchObject(_NoteData[13 ].data)
	expect(new Note(10 )).toMatchObject(_NoteData[14 ].data)
	expect(new Note(11 )).toMatchObject(_NoteData[16 ].data)
	expect(new Note(12 )).toMatchObject(_NoteData[17 ].data)
	expect(new Note(13 )).toMatchObject(_NoteData[18 ].data)
	expect(new Note(14 )).toMatchObject(_NoteData[20 ].data)
	expect(new Note(15 )).toMatchObject(_NoteData[21 ].data)
	expect(new Note(16 )).toMatchObject(_NoteData[23 ].data)
	expect(new Note(17 )).toMatchObject(_NoteData[24 ].data)
	expect(new Note(18 )).toMatchObject(_NoteData[25 ].data)
	expect(new Note(19 )).toMatchObject(_NoteData[27 ].data)
	expect(new Note(20 )).toMatchObject(_NoteData[28 ].data)
	expect(new Note(21 )).toMatchObject(_NoteData[30 ].data)
	expect(new Note(22 )).toMatchObject(_NoteData[31 ].data)
	expect(new Note(23 )).toMatchObject(_NoteData[33 ].data)
	expect(new Note(24 )).toMatchObject(_NoteData[34 ].data)
	expect(new Note(25 )).toMatchObject(_NoteData[35 ].data)
	expect(new Note(26 )).toMatchObject(_NoteData[37 ].data)
	expect(new Note(27 )).toMatchObject(_NoteData[38 ].data)
	expect(new Note(28 )).toMatchObject(_NoteData[40 ].data)
	expect(new Note(29 )).toMatchObject(_NoteData[41 ].data)
	expect(new Note(30 )).toMatchObject(_NoteData[42 ].data)
	expect(new Note(31 )).toMatchObject(_NoteData[44 ].data)
	expect(new Note(32 )).toMatchObject(_NoteData[45 ].data)
	expect(new Note(33 )).toMatchObject(_NoteData[47 ].data)
	expect(new Note(34 )).toMatchObject(_NoteData[48 ].data)
	expect(new Note(35 )).toMatchObject(_NoteData[50 ].data)
	expect(new Note(36 )).toMatchObject(_NoteData[51 ].data)
	expect(new Note(37 )).toMatchObject(_NoteData[52 ].data)
	expect(new Note(38 )).toMatchObject(_NoteData[54 ].data)
	expect(new Note(39 )).toMatchObject(_NoteData[55 ].data)
	expect(new Note(40 )).toMatchObject(_NoteData[57 ].data)
	expect(new Note(41 )).toMatchObject(_NoteData[58 ].data)
	expect(new Note(42 )).toMatchObject(_NoteData[59 ].data)
	expect(new Note(43 )).toMatchObject(_NoteData[61 ].data)
	expect(new Note(44 )).toMatchObject(_NoteData[62 ].data)
	expect(new Note(45 )).toMatchObject(_NoteData[64 ].data)
	expect(new Note(46 )).toMatchObject(_NoteData[65 ].data)
	expect(new Note(47 )).toMatchObject(_NoteData[67 ].data)
	expect(new Note(48 )).toMatchObject(_NoteData[68 ].data)
	expect(new Note(49 )).toMatchObject(_NoteData[69 ].data)
	expect(new Note(50 )).toMatchObject(_NoteData[71 ].data)
	expect(new Note(51 )).toMatchObject(_NoteData[72 ].data)
	expect(new Note(52 )).toMatchObject(_NoteData[74 ].data)
	expect(new Note(53 )).toMatchObject(_NoteData[75 ].data)
	expect(new Note(54 )).toMatchObject(_NoteData[76 ].data)
	expect(new Note(55 )).toMatchObject(_NoteData[78 ].data)
	expect(new Note(56 )).toMatchObject(_NoteData[79 ].data)
	expect(new Note(57 )).toMatchObject(_NoteData[81 ].data)
	expect(new Note(58 )).toMatchObject(_NoteData[82 ].data)
	expect(new Note(59 )).toMatchObject(_NoteData[84 ].data)
	expect(new Note(60 )).toMatchObject(_NoteData[85 ].data)
	expect(new Note(61 )).toMatchObject(_NoteData[86 ].data)
	expect(new Note(62 )).toMatchObject(_NoteData[88 ].data)
	expect(new Note(63 )).toMatchObject(_NoteData[89 ].data)
	expect(new Note(64 )).toMatchObject(_NoteData[91 ].data)
	expect(new Note(65 )).toMatchObject(_NoteData[92 ].data)
	expect(new Note(66 )).toMatchObject(_NoteData[93 ].data)
	expect(new Note(67 )).toMatchObject(_NoteData[95 ].data)
	expect(new Note(68 )).toMatchObject(_NoteData[96 ].data)
	expect(new Note(69 )).toMatchObject(_NoteData[98 ].data)
	expect(new Note(70 )).toMatchObject(_NoteData[99 ].data)
	expect(new Note(71 )).toMatchObject(_NoteData[101].data)
	expect(new Note(72 )).toMatchObject(_NoteData[102].data)
	expect(new Note(73 )).toMatchObject(_NoteData[103].data)
	expect(new Note(74 )).toMatchObject(_NoteData[105].data)
	expect(new Note(75 )).toMatchObject(_NoteData[106].data)
	expect(new Note(76 )).toMatchObject(_NoteData[108].data)
	expect(new Note(77 )).toMatchObject(_NoteData[109].data)
	expect(new Note(78 )).toMatchObject(_NoteData[110].data)
	expect(new Note(79 )).toMatchObject(_NoteData[112].data)
	expect(new Note(80 )).toMatchObject(_NoteData[113].data)
	expect(new Note(81 )).toMatchObject(_NoteData[115].data)
	expect(new Note(82 )).toMatchObject(_NoteData[116].data)
	expect(new Note(83 )).toMatchObject(_NoteData[118].data)
	expect(new Note(84 )).toMatchObject(_NoteData[119].data)
	expect(new Note(85 )).toMatchObject(_NoteData[120].data)
	expect(new Note(86 )).toMatchObject(_NoteData[122].data)
	expect(new Note(87 )).toMatchObject(_NoteData[123].data)
	expect(new Note(88 )).toMatchObject(_NoteData[125].data)
	expect(new Note(89 )).toMatchObject(_NoteData[126].data)
	expect(new Note(90 )).toMatchObject(_NoteData[127].data)
	expect(new Note(91 )).toMatchObject(_NoteData[129].data)
	expect(new Note(92 )).toMatchObject(_NoteData[130].data)
	expect(new Note(93 )).toMatchObject(_NoteData[132].data)
	expect(new Note(94 )).toMatchObject(_NoteData[133].data)
	expect(new Note(95 )).toMatchObject(_NoteData[135].data)
	expect(new Note(96 )).toMatchObject(_NoteData[136].data)
	expect(new Note(97 )).toMatchObject(_NoteData[137].data)
	expect(new Note(98 )).toMatchObject(_NoteData[139].data)
	expect(new Note(99 )).toMatchObject(_NoteData[140].data)
	expect(new Note(100)).toMatchObject(_NoteData[142].data)
	expect(new Note(101)).toMatchObject(_NoteData[143].data)
	expect(new Note(102)).toMatchObject(_NoteData[144].data)
	expect(new Note(103)).toMatchObject(_NoteData[146].data)
	expect(new Note(104)).toMatchObject(_NoteData[147].data)
	expect(new Note(105)).toMatchObject(_NoteData[149].data)
	expect(new Note(106)).toMatchObject(_NoteData[150].data)
	expect(new Note(107)).toMatchObject(_NoteData[152].data)
	expect(new Note(108)).toMatchObject(_NoteData[153].data)
	expect(new Note(109)).toMatchObject(_NoteData[154].data)
	expect(new Note(110)).toMatchObject(_NoteData[156].data)
	expect(new Note(111)).toMatchObject(_NoteData[157].data)
	expect(new Note(112)).toMatchObject(_NoteData[159].data)
	expect(new Note(113)).toMatchObject(_NoteData[160].data)
	expect(new Note(114)).toMatchObject(_NoteData[161].data)
	expect(new Note(115)).toMatchObject(_NoteData[163].data)
	expect(new Note(116)).toMatchObject(_NoteData[164].data)
	expect(new Note(117)).toMatchObject(_NoteData[166].data)
	expect(new Note(118)).toMatchObject(_NoteData[167].data)
	expect(new Note(119)).toMatchObject(_NoteData[169].data)
	expect(new Note(120)).toMatchObject(_NoteData[170].data)
	expect(new Note(121)).toMatchObject(_NoteData[171].data)
	expect(new Note(122)).toMatchObject(_NoteData[173].data)
	expect(new Note(123)).toMatchObject(_NoteData[174].data)
	expect(new Note(124)).toMatchObject(_NoteData[176].data)
	expect(new Note(125)).toMatchObject(_NoteData[177].data)
	expect(new Note(126)).toMatchObject(_NoteData[178].data)
	expect(new Note(127)).toMatchObject(_NoteData[180].data)
})
