//###  Module  ###//
import {Note       } from "../__Main__"
import DefaultValues from "../DefaultValues"


//#####################//
//###  Test.Values  ###//
//#####################//

test("Values", ()=>{
	expect(Note.C_Negative1 ).toMatchObject(new Note("C-1" ))
	expect(Note.C$_Negative1).toMatchObject(new Note("C#-1"))
	expect(Note.Db_Negative1).toMatchObject(new Note("Db-1"))
	expect(Note.D_Negative1 ).toMatchObject(new Note("D-1" ))
	expect(Note.D$_Negative1).toMatchObject(new Note("D#-1"))
	expect(Note.Eb_Negative1).toMatchObject(new Note("Eb-1"))
	expect(Note.E_Negative1 ).toMatchObject(new Note("E-1" ))
	expect(Note.F_Negative1 ).toMatchObject(new Note("F-1" ))
	expect(Note.F$_Negative1).toMatchObject(new Note("F#-1"))
	expect(Note.Gb_Negative1).toMatchObject(new Note("Gb-1"))
	expect(Note.G_Negative1 ).toMatchObject(new Note("G-1" ))
	expect(Note.G$_Negative1).toMatchObject(new Note("G#-1"))
	expect(Note.Ab_Negative1).toMatchObject(new Note("Ab-1"))
	expect(Note.A_Negative1 ).toMatchObject(new Note("A-1" ))
	expect(Note.A$_Negative1).toMatchObject(new Note("A#-1"))
	expect(Note.Bb_Negative1).toMatchObject(new Note("Bb-1"))
	expect(Note.B_Negative1 ).toMatchObject(new Note("B-1" ))
	expect(Note.C0          ).toMatchObject(new Note("C0"  ))
	expect(Note.C$0         ).toMatchObject(new Note("C#0" ))
	expect(Note.Db0         ).toMatchObject(new Note("Db0" ))
	expect(Note.D0          ).toMatchObject(new Note("D0"  ))
	expect(Note.D$0         ).toMatchObject(new Note("D#0" ))
	expect(Note.Eb0         ).toMatchObject(new Note("Eb0" ))
	expect(Note.E0          ).toMatchObject(new Note("E0"  ))
	expect(Note.F0          ).toMatchObject(new Note("F0"  ))
	expect(Note.F$0         ).toMatchObject(new Note("F#0" ))
	expect(Note.Gb0         ).toMatchObject(new Note("Gb0" ))
	expect(Note.G0          ).toMatchObject(new Note("G0"  ))
	expect(Note.G$0         ).toMatchObject(new Note("G#0" ))
	expect(Note.Ab0         ).toMatchObject(new Note("Ab0" ))
	expect(Note.A0          ).toMatchObject(new Note("A0"  ))
	expect(Note.A$0         ).toMatchObject(new Note("A#0" ))
	expect(Note.Bb0         ).toMatchObject(new Note("Bb0" ))
	expect(Note.B0          ).toMatchObject(new Note("B0"  ))
	expect(Note.C1          ).toMatchObject(new Note("C1"  ))
	expect(Note.C$1         ).toMatchObject(new Note("C#1" ))
	expect(Note.Db1         ).toMatchObject(new Note("Db1" ))
	expect(Note.D1          ).toMatchObject(new Note("D1"  ))
	expect(Note.D$1         ).toMatchObject(new Note("D#1" ))
	expect(Note.Eb1         ).toMatchObject(new Note("Eb1" ))
	expect(Note.E1          ).toMatchObject(new Note("E1"  ))
	expect(Note.F1          ).toMatchObject(new Note("F1"  ))
	expect(Note.F$1         ).toMatchObject(new Note("F#1" ))
	expect(Note.Gb1         ).toMatchObject(new Note("Gb1" ))
	expect(Note.G1          ).toMatchObject(new Note("G1"  ))
	expect(Note.G$1         ).toMatchObject(new Note("G#1" ))
	expect(Note.Ab1         ).toMatchObject(new Note("Ab1" ))
	expect(Note.A1          ).toMatchObject(new Note("A1"  ))
	expect(Note.A$1         ).toMatchObject(new Note("A#1" ))
	expect(Note.Bb1         ).toMatchObject(new Note("Bb1" ))
	expect(Note.B1          ).toMatchObject(new Note("B1"  ))
	expect(Note.C2          ).toMatchObject(new Note("C2"  ))
	expect(Note.C$2         ).toMatchObject(new Note("C#2" ))
	expect(Note.Db2         ).toMatchObject(new Note("Db2" ))
	expect(Note.D2          ).toMatchObject(new Note("D2"  ))
	expect(Note.D$2         ).toMatchObject(new Note("D#2" ))
	expect(Note.Eb2         ).toMatchObject(new Note("Eb2" ))
	expect(Note.E2          ).toMatchObject(new Note("E2"  ))
	expect(Note.F2          ).toMatchObject(new Note("F2"  ))
	expect(Note.F$2         ).toMatchObject(new Note("F#2" ))
	expect(Note.Gb2         ).toMatchObject(new Note("Gb2" ))
	expect(Note.G2          ).toMatchObject(new Note("G2"  ))
	expect(Note.G$2         ).toMatchObject(new Note("G#2" ))
	expect(Note.Ab2         ).toMatchObject(new Note("Ab2" ))
	expect(Note.A2          ).toMatchObject(new Note("A2"  ))
	expect(Note.A$2         ).toMatchObject(new Note("A#2" ))
	expect(Note.Bb2         ).toMatchObject(new Note("Bb2" ))
	expect(Note.B2          ).toMatchObject(new Note("B2"  ))
	expect(Note.C3          ).toMatchObject(new Note("C3"  ))
	expect(Note.C$3         ).toMatchObject(new Note("C#3" ))
	expect(Note.Db3         ).toMatchObject(new Note("Db3" ))
	expect(Note.D3          ).toMatchObject(new Note("D3"  ))
	expect(Note.D$3         ).toMatchObject(new Note("D#3" ))
	expect(Note.Eb3         ).toMatchObject(new Note("Eb3" ))
	expect(Note.E3          ).toMatchObject(new Note("E3"  ))
	expect(Note.F3          ).toMatchObject(new Note("F3"  ))
	expect(Note.F$3         ).toMatchObject(new Note("F#3" ))
	expect(Note.Gb3         ).toMatchObject(new Note("Gb3" ))
	expect(Note.G3          ).toMatchObject(new Note("G3"  ))
	expect(Note.G$3         ).toMatchObject(new Note("G#3" ))
	expect(Note.Ab3         ).toMatchObject(new Note("Ab3" ))
	expect(Note.A3          ).toMatchObject(new Note("A3"  ))
	expect(Note.A$3         ).toMatchObject(new Note("A#3" ))
	expect(Note.Bb3         ).toMatchObject(new Note("Bb3" ))
	expect(Note.B3          ).toMatchObject(new Note("B3"  ))
	expect(Note.C4          ).toMatchObject(new Note("C4"  ))
	expect(Note.C$4         ).toMatchObject(new Note("C#4" ))
	expect(Note.Db4         ).toMatchObject(new Note("Db4" ))
	expect(Note.D4          ).toMatchObject(new Note("D4"  ))
	expect(Note.D$4         ).toMatchObject(new Note("D#4" ))
	expect(Note.Eb4         ).toMatchObject(new Note("Eb4" ))
	expect(Note.E4          ).toMatchObject(new Note("E4"  ))
	expect(Note.F4          ).toMatchObject(new Note("F4"  ))
	expect(Note.F$4         ).toMatchObject(new Note("F#4" ))
	expect(Note.Gb4         ).toMatchObject(new Note("Gb4" ))
	expect(Note.G4          ).toMatchObject(new Note("G4"  ))
	expect(Note.G$4         ).toMatchObject(new Note("G#4" ))
	expect(Note.Ab4         ).toMatchObject(new Note("Ab4" ))
	expect(Note.A4          ).toMatchObject(new Note("A4"  ))
	expect(Note.A$4         ).toMatchObject(new Note("A#4" ))
	expect(Note.Bb4         ).toMatchObject(new Note("Bb4" ))
	expect(Note.B4          ).toMatchObject(new Note("B4"  ))
	expect(Note.C5          ).toMatchObject(new Note("C5"  ))
	expect(Note.C$5         ).toMatchObject(new Note("C#5" ))
	expect(Note.Db5         ).toMatchObject(new Note("Db5" ))
	expect(Note.D5          ).toMatchObject(new Note("D5"  ))
	expect(Note.D$5         ).toMatchObject(new Note("D#5" ))
	expect(Note.Eb5         ).toMatchObject(new Note("Eb5" ))
	expect(Note.E5          ).toMatchObject(new Note("E5"  ))
	expect(Note.F5          ).toMatchObject(new Note("F5"  ))
	expect(Note.F$5         ).toMatchObject(new Note("F#5" ))
	expect(Note.Gb5         ).toMatchObject(new Note("Gb5" ))
	expect(Note.G5          ).toMatchObject(new Note("G5"  ))
	expect(Note.G$5         ).toMatchObject(new Note("G#5" ))
	expect(Note.Ab5         ).toMatchObject(new Note("Ab5" ))
	expect(Note.A5          ).toMatchObject(new Note("A5"  ))
	expect(Note.A$5         ).toMatchObject(new Note("A#5" ))
	expect(Note.Bb5         ).toMatchObject(new Note("Bb5" ))
	expect(Note.B5          ).toMatchObject(new Note("B5"  ))
	expect(Note.C6          ).toMatchObject(new Note("C6"  ))
	expect(Note.C$6         ).toMatchObject(new Note("C#6" ))
	expect(Note.Db6         ).toMatchObject(new Note("Db6" ))
	expect(Note.D6          ).toMatchObject(new Note("D6"  ))
	expect(Note.D$6         ).toMatchObject(new Note("D#6" ))
	expect(Note.Eb6         ).toMatchObject(new Note("Eb6" ))
	expect(Note.E6          ).toMatchObject(new Note("E6"  ))
	expect(Note.F6          ).toMatchObject(new Note("F6"  ))
	expect(Note.F$6         ).toMatchObject(new Note("F#6" ))
	expect(Note.Gb6         ).toMatchObject(new Note("Gb6" ))
	expect(Note.G6          ).toMatchObject(new Note("G6"  ))
	expect(Note.G$6         ).toMatchObject(new Note("G#6" ))
	expect(Note.Ab6         ).toMatchObject(new Note("Ab6" ))
	expect(Note.A6          ).toMatchObject(new Note("A6"  ))
	expect(Note.A$6         ).toMatchObject(new Note("A#6" ))
	expect(Note.Bb6         ).toMatchObject(new Note("Bb6" ))
	expect(Note.B6          ).toMatchObject(new Note("B6"  ))
	expect(Note.C7          ).toMatchObject(new Note("C7"  ))
	expect(Note.C$7         ).toMatchObject(new Note("C#7" ))
	expect(Note.Db7         ).toMatchObject(new Note("Db7" ))
	expect(Note.D7          ).toMatchObject(new Note("D7"  ))
	expect(Note.D$7         ).toMatchObject(new Note("D#7" ))
	expect(Note.Eb7         ).toMatchObject(new Note("Eb7" ))
	expect(Note.E7          ).toMatchObject(new Note("E7"  ))
	expect(Note.F7          ).toMatchObject(new Note("F7"  ))
	expect(Note.F$7         ).toMatchObject(new Note("F#7" ))
	expect(Note.Gb7         ).toMatchObject(new Note("Gb7" ))
	expect(Note.G7          ).toMatchObject(new Note("G7"  ))
	expect(Note.G$7         ).toMatchObject(new Note("G#7" ))
	expect(Note.Ab7         ).toMatchObject(new Note("Ab7" ))
	expect(Note.A7          ).toMatchObject(new Note("A7"  ))
	expect(Note.A$7         ).toMatchObject(new Note("A#7" ))
	expect(Note.Bb7         ).toMatchObject(new Note("Bb7" ))
	expect(Note.B7          ).toMatchObject(new Note("B7"  ))
	expect(Note.C8          ).toMatchObject(new Note("C8"  ))
	expect(Note.C$8         ).toMatchObject(new Note("C#8" ))
	expect(Note.Db8         ).toMatchObject(new Note("Db8" ))
	expect(Note.D8          ).toMatchObject(new Note("D8"  ))
	expect(Note.D$8         ).toMatchObject(new Note("D#8" ))
	expect(Note.Eb8         ).toMatchObject(new Note("Eb8" ))
	expect(Note.E8          ).toMatchObject(new Note("E8"  ))
	expect(Note.F8          ).toMatchObject(new Note("F8"  ))
	expect(Note.F$8         ).toMatchObject(new Note("F#8" ))
	expect(Note.Gb8         ).toMatchObject(new Note("Gb8" ))
	expect(Note.G8          ).toMatchObject(new Note("G8"  ))
	expect(Note.G$8         ).toMatchObject(new Note("G#8" ))
	expect(Note.Ab8         ).toMatchObject(new Note("Ab8" ))
	expect(Note.A8          ).toMatchObject(new Note("A8"  ))
	expect(Note.A$8         ).toMatchObject(new Note("A#8" ))
	expect(Note.Bb8         ).toMatchObject(new Note("Bb8" ))
	expect(Note.B8          ).toMatchObject(new Note("B8"  ))
	expect(Note.C9          ).toMatchObject(new Note("C9"  ))
	expect(Note.C$9         ).toMatchObject(new Note("C#9" ))
	expect(Note.Db9         ).toMatchObject(new Note("Db9" ))
	expect(Note.D9          ).toMatchObject(new Note("D9"  ))
	expect(Note.D$9         ).toMatchObject(new Note("D#9" ))
	expect(Note.Eb9         ).toMatchObject(new Note("Eb9" ))
	expect(Note.E9          ).toMatchObject(new Note("E9"  ))
	expect(Note.F9          ).toMatchObject(new Note("F9"  ))
	expect(Note.F$9         ).toMatchObject(new Note("F#9" ))
	expect(Note.Gb9         ).toMatchObject(new Note("Gb9" ))
	expect(Note.G9          ).toMatchObject(new Note("G9"  ))
})


//#######################################//
//###  Test.GetterReturnsNewInstance  ###//
//#######################################//

test("GetterReturnsNewInstance", ()=>{
	const c4 = Note.C4

	//###  Velocity  ###//
	Note.C4.velocity = 100
	expect(c4.velocity     ).toEqual(DefaultValues.velocity)
	expect(Note.C4.velocity).toEqual(DefaultValues.velocity)
	//----------------------------------------------------//
	c4.velocity = 100
	expect(c4.velocity     ).toEqual(100)
	expect(Note.C4.velocity).toEqual(DefaultValues.velocity)
})
